name: Retry Matrix Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  retry-job:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        attempt: [1, 2, 3]

    runs-on: ubuntu-latest
    continue-on-error: true
    # Fixed: Use a single output rather than dynamic output names
    outputs:
      success: ${{ steps.set-success.outputs.success }}

    steps:
      # Check if any previous attempt was successful by looking for a cache hit
      - name: Check for previous success
        id: check-cache
        uses: actions/cache@v3
        with:
          path: ~/.success-marker
          key: success-marker-${{ github.run_id }}
          restore-keys: success-marker-${{ github.run_id }}

      # Skip this attempt if cache was found (previous attempt succeeded)
      - name: Skip if previous success
        if: steps.check-cache.outputs.cache-hit == 'true'
        run: |
          echo "A previous attempt was successful, skipping this attempt"
          exit 0

      - name: Echo attempt number
        id: run-attempt
        run: |
          echo "This is attempt ${{ matrix.attempt }}"
          # Fail first attempt, succeed on others
          if [ "${{ matrix.attempt }}" = "1" ]; then
            exit 1
          else
            exit 0
          fi
      
      - name: Set success output
        id: set-success
        if: success()
        run: |
          echo "success=true" >> $GITHUB_OUTPUT
          mkdir -p ~/.success-marker
          echo "success" > ~/.success-marker/marker
      
      # Save success cache if this attempt succeeded
      - name: Save success cache
        if: steps.set-success.outputs.success == 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.success-marker
          key: success-marker-${{ github.run_id }}

  check-matrix-success:
    needs: retry-job
    runs-on: ubuntu-latest
    steps:
      # Fixed: Changed how we check for success across matrix jobs
      - name: Check if any attempt succeeded
        run: |
          if [[ "${{ contains(needs.retry-job.outputs.*.success, 'true') }}" == "true" ]]; then
            echo "At least one attempt succeeded"
          else
            echo "All attempts failed"
            exit 1
          fi

  follow-up-job:
    needs: check-matrix-success
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo completion message
        run: |
          echo "The retry-job has completed successfully!"
          echo "This job runs after retry-job succeeds"
