name: Retry Matrix Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Add a job to track success state
  attempt-tracker:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.init.outputs.success }}
    steps:
      - id: init
        run: echo "success=false" >> $GITHUB_OUTPUT

  retry-job:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        # This creates 3 attempts
        attempt: [1, 2, 3]

    needs: attempt-tracker
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      matrix-success: ${{ steps.check-success.outputs.success }}

    # Skip subsequent attempts if any previous attempt succeeded
    if: ${{ needs.attempt-tracker.outputs.success != 'true' }}

    steps:
      - name: Check previous attempts
        id: check-previous
        if: ${{ matrix.attempt > 1 }}
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: attempt-success
          path: /tmp

      - name: Skip if previous attempt succeeded
        id: skip-check
        if: ${{ matrix.attempt > 1 }}
        run: |
          if [ -f "/tmp/success" ]; then
            echo "Previous attempt succeeded, skipping this attempt"
            exit 0
          fi
          
      - name: Echo attempt number
        id: run-attempt
        run: |
          echo "This is attempt ${{ matrix.attempt }}"
          # Fail first attempt, succeed on others
          if [ "${{ matrix.attempt }}" = "1" ]; then
            exit 1
          else
            exit 0
          fi
      
      - name: Check success status
        id: check-success
        if: success()
        run: |
          echo "success=true" >> $GITHUB_OUTPUT
          mkdir -p /tmp/artifacts
          echo "true" > /tmp/artifacts/success
      
      - name: Upload success marker
        if: steps.check-success.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: attempt-success
          path: /tmp/artifacts/success
          retention-days: 1

  # Dummy aggregator job that succeeds if any matrix job succeeds
  # and explicitly fails if none succeeded
  check-matrix-success:
    needs: retry-job
    runs-on: ubuntu-latest
    steps:
      - name: Check if any attempt succeeded
        run: |
          if [[ "${{ contains(needs.retry-job.outputs.*.matrix-success, 'true') }}" == "true" ]]; then
            echo "At least one attempt succeeded"
          else
            echo "All attempts failed"
            exit 1
          fi

  follow-up-job:
    needs: check-matrix-success
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo completion message
        run: |
          echo "The retry-job has completed successfully!"
          echo "This job runs after retry-job succeeds"
