name: Retry Matrix Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
    retry:
        runs-on: ubuntu-latest
        # Add permissions needed for GitHub API
        permissions:
          contents: read
          actions: read
        strategy:
            matrix:
                attempt: [1, 2, 3]
        continue-on-error: true
        name: retry-${{ matrix.attempt }}
        steps:
            - name: Check for Artifact
              id: check-artifact
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                # Look for artifacts in the current workflow run only
                artifacts=$(gh api \
                  repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
                  --jq '.artifacts[].name')
                if echo "$artifacts" | grep -q "success-artifact"; then
                  echo "Skipping attempt ${{ matrix.attempt }} because a previous attempt succeeded"
                  exit 78
                else
                  echo "found nothing, proceeding"
                fi

            - name: Do stuff
              id: do-stuff
              run: |
                echo "doing stuff, attempt number ${{ matrix.attempt }}"
                if [ "${{ matrix.attempt }}" != "2" ]; then
                    echo "arbitrary failure on 1st attempt (and 3rd attempt if I make it this far)"
                    exit 1
                fi                

            - name: record-success
              id: record-success
              run: |
                echo "doing stuff, attempt number ${{ matrix.attempt }}"
                # succeeding on the second attempt. recording a file
                if [ "${{ matrix.attempt }}" = "2" ]; then
                    touch success.txt
                fi
            
            - name: Upload success artifact if it exists
              id: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: success-artifact
                path: success.txt
                if-no-files-found: ignore

    # New follow-up job that runs after retry job
    follow-up:
        needs: retry
        runs-on: ubuntu-latest
        # Add permissions needed for GitHub API
        permissions:
          contents: read
          actions: read
        steps:
            - name: Check for success artifact
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                # Check for success artifact from any retry attempt
                artifacts=$(gh api \
                  repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
                  --jq '.artifacts[].name')
                if echo "$artifacts" | grep -q "success-artifact"; then
                  echo "At least one retry attempt succeeded!"
                else
                  echo "All retry attempts failed"
                  exit 1
                fi
                
            - name: Run follow-up tasks
              run: |
                echo "Running follow-up tasks after successful retry"
                echo "This job only executes if at least one retry attempt succeeded"

