name: Retry Matrix Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job to track which attempts should be skipped
  attempt-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Create attempt status file
        run: |
          mkdir -p ~/attempt-status
          echo "false" > ~/attempt-status/success
      
      - name: Upload attempt status
        uses: actions/upload-artifact@v4
        with:
          name: attempt-status
          path: ~/attempt-status
          retention-days: 1

  retry-job:
    strategy:
      matrix:
        attempt: [1, 2, 3]
      fail-fast: false
      max-parallel: 1

    runs-on: ubuntu-latest
    needs: attempt-tracker
    continue-on-error: true
    name: retry-${{ matrix.attempt }}
    
    steps:
      # Download the shared status file
      - name: Download attempt status
        uses: actions/download-artifact@v4
        with:
          name: attempt-status
          path: ~/attempt-status
      
      # Read the status file to check if previous attempts succeeded
      - name: Check previous success
        id: check-status
        run: |
          if [[ "$(cat ~/attempt-status/success)" == "true" ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi
      
      # Skip this attempt if a previous one succeeded
      - name: Skip on previous success
        if: steps.check-status.outputs.should_skip == 'true'
        run: |
          echo "Skipping attempt ${{ matrix.attempt }} because a previous attempt succeeded"
          exit 0
      
      # Run the actual attempt
      - name: Run attempt
        id: run-attempt
        if: steps.check-status.outputs.should_skip != 'true'
        run: |
          echo "This is attempt ${{ matrix.attempt }}"
          if [ "${{ matrix.attempt }}" = "1" ]; then
            exit 1
          else
            exit 0
          fi
      
      # Update status if successful
      - name: Record success
        if: success() && steps.check-status.outputs.should_skip != 'true'
        run: |
          echo "true" > ~/attempt-status/success
          echo "Success in attempt ${{ matrix.attempt }}"
      
      # Upload updated status for future matrix jobs
      - name: Upload updated status
        if: always() && steps.check-status.outputs.should_skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: attempt-status
          path: ~/attempt-status
          retention-days: 1

  # Special job to extract final status
  check-success:
    needs: retry-job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download final status
        uses: actions/download-artifact@v4
        with:
          name: attempt-status
          path: ~/attempt-status
      
      - name: Check final result
        run: |
          if [[ "$(cat ~/attempt-status/success)" == "true" ]]; then
            echo "At least one attempt succeeded"
          else
            echo "All attempts failed"
            exit 1
          fi

  follow-up-job:
    needs: check-success
    runs-on: ubuntu-latest
    steps:
      - name: Echo completion message
        run: |
          echo "The retry job has completed successfully!"
          echo "This job runs after retry-job succeeds"
