name: Retry Matrix Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Add a coordinator job to track success state
  attempt-coordinator:
    runs-on: ubuntu-latest
    outputs:
      has-previous-success: 'false'
    steps:
      - run: echo "Initialize coordinator job"

  retry-job:
    needs: attempt-coordinator
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        attempt: [1, 2, 3]
    
    # Adding an ID for each matrix job for tracking purposes
    name: retry-${{ matrix.attempt }}
    id: retry-${{ matrix.attempt }}
    
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      success: ${{ steps.set-success.outputs.success }}

    # Only run if we're on the first attempt OR previous attempts have all failed
    if: ${{ matrix.attempt == 1 || needs.attempt-coordinator.outputs.has-previous-success == 'false' }}

    steps:
      - name: Echo attempt number
        id: run-attempt
        run: |
          echo "This is attempt ${{ matrix.attempt }}"
          # Fail first attempt, succeed on others
          if [ "${{ matrix.attempt }}" = "1" ]; then
            exit 1
          else
            exit 0
          fi
      
      - name: Set success output
        id: set-success
        if: success()
        run: echo "success=true" >> $GITHUB_OUTPUT
      
      # Write a marker file if successful
      - name: Signal success to next jobs
        if: success()
        run: |
          echo "Success in attempt ${{ matrix.attempt }}"
          # Update the coordinator output for next attempts
          echo "has-previous-success=true" >> $GITHUB_ENV

  # Use a separate job to check overall success
  check-matrix-success:
    needs: retry-job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check if any attempt succeeded
        run: |
          # Debug output to see what we're working with
          echo "Job outputs: ${{ toJSON(needs.retry-job.outputs) }}"
          echo "Job result: ${{ needs.retry-job.result }}"
          
          if [[ "${{ contains(needs.retry-job.outputs.*.success, 'true') }}" == "true" ]]; then
            echo "At least one attempt succeeded"
            exit 0
          else
            echo "All attempts failed"
            exit 1
          fi

  follow-up-job:
    needs: check-matrix-success
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo completion message
        run: |
          echo "The retry-job has completed successfully!"
          echo "This job runs after retry-job succeeds"
